### ISSUE TITLE
outdated code

### ISSUE THREAD

**Issue by arch-user-france1** [zxul767/pawn#8] opened 2022-01-19 20:51 UTC
the code of the script is outdated

**Comment by zxul767** [comment] 2022-03-09 18:43
Thanks for the report! 

The issue is now fixed in `master` and more detailed instructions to run it are now in the `README`. Let me know if you find any other issues.

**Comment by arch-user-france1** [comment] 2022-03-12 09:14
Still not fixed: /usr/include/c++/11.2.0/bits/hashtable_policy.h:1215:23: hash function must be invocable with an argument of key type
/usr/include/c++/11.2.0/bits/hashtable_policy.h:1217:25: »(const game_rules::BoardConfigurationTracker::board_hasher) (const game_rules::BoardKey&)«

 1217 |         return _M_hash()(__k);
      |                ~~~~~~~~~^~~~~

git branch == master

**Comment by arch-user-france1** [comment] 2022-03-12 09:15
gcc version: gcc (GCC) 11.2.0

**Comment by zxul767** [comment] 2022-03-12 20:08
Great catch, I was testing with an older version of `g++`. Luckily the changes to make it work with the `g++11` version were minimal. They're now in `master`

**Comment by arch-user-france1** [comment] 2022-03-13 15:38
It works :) Thanks.

**Comment by zxul767** [comment] 2022-03-13 21:47
Closing as fixed by #12

**Closed as completed by zxul767** 2022-03-13 21:47 UTC
